### PR TITLE
feat: better mobile support

### PR DESCRIPTION
**Pull request by TobiTenno**
todo:
- [x] get overview bar smaller
- [x] if it's easier, drop the image and the text on mobile in overview

### CODE REVIEW

**Comment by TobiTenno** [comment]
@jkuester i think i got it in the sweet spot now. i got the nice fonts showing all the time, i _think_

**Comment by TobiTenno** [comment]
scratch that

**Comment by TobiTenno** [comment]
ok, now it's doing what i wanted it to

**Comment by Holyphoenix** [comment]
I recommend style encapsulation (shadowdom) with styles attached to the components themselves over antiquated global style sheets. It would help you avoid crazy amounts of "!important" tags.

**Comment by TobiTenno** [comment]
> [...] style encapsulation [...] over antiquated global style sheets [...]

for the most part, these have been working fine, and for the time being on the style generation, i'd rather those be shared so that I can reflect the updates while I'm updating styles across the board in-browser.

the wild mass of !importants are all for overrides of base grid stuff, so i'd rather have those called out, even if i modularized the styles so they'd be manually attached

**Comment by TobiTenno** [comment]
but yeah, that's probably what I'll do next if I spend much more time updating the styles, i'm mostly trying to abstracting & encapsulating most of the functionality first, breaking them into black boxes, while getting the visibility manageable on mobile and any other form-factors i've missed over time, but then i'll probably do another pass through and add modular styles and some ui tests, since i don't have any of those at all

**Pull request merged**
